sudo: required

# This moves Kubernetes specific config files.
env:
  global:
    - CHANGE_MINIKUBE_NONE_USER=true
    - K8S_VERSION="v1.10.0"
    - MINIKUBE_VERSION="v0.28.2"
    - CHART_TESTING_VERSION="v1.0.3"
    - HELM_VERSION="v2.9.1"

# Some initial setup
before_install:
- sudo apt-get update
- sudo apt-get install -y socat util-linux

# Copy nsenter tool for Ubuntu 14.04 (current travisCI build VM version)
- sudo docker run --rm -v $(pwd):/target jpetazzo/nsenter
- sudo mv -fv nsenter /usr/local/bin/

before_script:
# Download kubectl, which is a requirement for using minikube.
- curl -Lo kubectl https://storage.googleapis.com/kubernetes-release/release/${K8S_VERSION}/bin/linux/amd64/kubectl && chmod +x kubectl && sudo mv kubectl /usr/local/bin/
# Download helm cli
- curl -o helm.tar.gz https://storage.googleapis.com/kubernetes-helm/helm-${HELM_VERSION}-linux-amd64.tar.gz && tar -xzf helm.tar.gz -C . && chmod +x ./linux-amd64/helm && sudo mv ./linux-amd64/helm /usr/local/bin/
# Download minikube.
- curl -Lo minikube https://github.com/kubernetes/minikube/releases/download/${MINIKUBE_VERSION}/minikube-linux-amd64 && chmod +x minikube && sudo mv minikube /usr/local/bin/
# TODO: remove the --bootstrapper flag once this issue is solved: https://github.com/kubernetes/minikube/issues/2704
- sudo minikube config set WantReportErrorPrompt false
- sudo -E minikube start --cpus 4 --memory 4096 --vm-driver=none --bootstrapper=localkube --kubernetes-version=${K8S_VERSION} --extra-config=apiserver.Authorization.Mode=RBAC
# Fix the kubectl context, as it's often stale.
- minikube update-context
# Wait for Kubernetes to be up and ready.
- JSONPATH='{range .items[*]}{@.metadata.name}:{range @.status.conditions[*]}{@.type}={@.status};{end}{end}'; until kubectl get nodes -o jsonpath="$JSONPATH" 2>&1 | grep -q "Ready=True"; do sleep 1; done

script:
- kubectl cluster-info
# Create cluster admin
- kubectl create clusterrolebinding add-on-cluster-admin --clusterrole=cluster-admin --serviceaccount=kube-system:default
# Set RABC rules for tiller
- kubectl -n kube-system create sa tiller && kubectl create clusterrolebinding tiller-cluster-rule --clusterrole=cluster-admin --serviceaccount=kube-system:tiller
# Install tiller
- helm init --service-account tiller
# Run charts-testing for stable charts
- docker run --rm -e KUBECONFIG="/home/travis/.kube/config" -e CHART_DIRS="stable" -v "/home:/home" -v "$(pwd):/workdir" --workdir /workdir gcr.io/kubernetes-charts-ci/chart-testing:${CHART_TESTING_VERSION} chart_test.sh --no-install

notifications:
  email: false
