elasticsearch:
  resources:
    requests:
      memory: "4Gi"
      cpu: "500m"
    limits:
      memory: "4Gi"
      cpu: "1"
  ## ElasticSearch xms and xmx should be same!
  javaOpts:
    xms: "3g"
    xmx: "3g"
mongodb:
  resources:
    requests:
      memory: "2Gi"
      cpu: "500m"
    limits:
      memory: "2Gi"
      cpu: "1"
  ## Make sure the --wiredTigerCacheSizeGB is
  ## no more than half the memory limit!
  ## This is critical to protect against
  ## OOMKill by Kubernetes!
  mongodbExtraFlags:
    - "--wiredTigerCacheSizeGB=1"
missionControl:
  resources:
    requests:
      memory: "2Gi"
      cpu: "500m"
    limits:
      memory: "4Gi"
      cpu: "1"
  javaOpts:
    xms: "2g"
    xmx: "4g"
insightServer:
  resources:
    requests:
      memory: "512Mi"
      cpu: "500m"
    limits:
      memory: "2Gi"
      cpu: "1"
insightExecutor:
  resources:
    requests:
      memory: "2Gi"
      cpu: "500m"
    limits:
      memory: "4Gi"
      cpu: "1"
  javaOpts:
    xms: "2g"
    xmx: "4g"
insightScheduler:
  resources:
    requests:
      memory: "512Mi"
      cpu: "500m"
    limits:
      memory: "2Gi"
      cpu: "1"
  javaOpts:
    xms: "512m"
    xmx: "2g"
