# Leave this file empty to ensure that CI runs builds against the default configuration in values.yaml.
# If this is an upgrade over an existing Mission Control 4.x, explicitly pass 'unifiedUpgradeAllowed=true' to upgrade
unifiedUpgradeAllowed: true
databaseUpgradeReady: true
missionControl:
  jfrogUrl: http://artifactory-artifactory.rt:8082
# To Fix ct tool --reuse-values - PASSWORDS ERROR: you must provide your current passwords when upgrade the release
postgresql:
  postgresqlPassword: password
  db:
    password: password
