# Default values for kubexray.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

imagePullSecrets:

image:
  repository: docker.bintray.io/kubexray
  # Note that by default we use appVersion to get image tag
  # tag:
  pullPolicy: Always

# Set the Xray config file, it sets access to Xray instance
# The key must be encoded with base64
# e.g. `cat xray_config.yaml | base64`
# It is only used if no existing secret is specified below
xrayConfig: ""

# Specify an existing secret holding the Xray config
existingSecret: ""

# Set kubexray scanning policy
scanPolicy:
  unscanned:
    # Whitelist namespaces
    whitelistNamespaces: "kube-system,kubexray"
    # Set for unscanned deployments delete/scaledown/ignore
    deployments: ignore
    # Set for unscanned statefulsets delete/scaledown/ignore
    statefulSets: ignore
  security:
    # Whitelist namespaces
    whitelistNamespaces: "kube-system,kubexray"
    # Set for deployments with security issues delete/scaledown/ignore
    deployments: ignore
    # Set for statefulsets with security issues delete/scaledown/ignore
    statefulSets: ignore
  license:
    # Whitelist namespaces
    whitelistNamespaces: "kube-system,kubexray"
    # Set for deployments with license issues delete/scaledown/ignore
    deployments: ignore
    # Set for statefulsets with license issues delete/scaledown/ignore
    statefulSets: ignore

# Set which user:group you want kubexray to be run with
# kubexray docker image already comes preset with rootless user
securityContext:
  enabled: true
  kubeXrayUserId: 1000
  kubeXrayGroupId: 1000

# Webhook REST API Service
service:
  port: 80
  ## Default type is ClusterIP, to expose externally use LoadBalancer
  ## On minikube use NodePort
  type: ClusterIP
  ## Provide static IP address
  loadBalancerIP:
  ## There are two available options: “Cluster” (default) and “Local”.
  externalTrafficPolicy: Cluster

# Webhook REST API ingress
ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
    # ingress.kubernetes.io/force-ssl-redirect: "true"
    # certmanager.k8s.io/cluster-issuer: "letsencrypt-prod"

  path: /
  hosts:
    - kubexray.example.com
  tls: []
  #  - secretName: kubexray.example.com
  #    hosts:
  #      - kubexray.example.com
# labels:
  # traffic-type: external
  # traffic-type: internal

env:
  logLevel: "INFO"

# Set resources
resources:
  limits:
    cpu: 256m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

# RBAC manifests management
rbac:
  enabled: true

nodeSelector: {}

tolerations: []

affinity: {}

# Enable and set Pod Disruption Budget
podDisruptionBudget:
  enabled: false
  maxUnavailable: 1
  minAvailable: null
