{{- if and .Values.access.accessConfig (not .Values.artifactory.unifiedSecretInstallation) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "artifactory.fullname" . }}-access-config
  labels:
    app: {{ template "artifactory.name" . }}
    chart: {{ template "artifactory.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
type: Opaque
stringData:
  access.config.patch.yml: |
{{ tpl (toYaml .Values.access.accessConfig) . | indent 4 }}
{{- end }}
