{{- if and (.Values.rtfs.persistence.federationProperties) (not .Values.rtfs.persistence.customFederationPropertiesConfig) .Values.rtfs.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "rtfs.fullname" . }}-properties
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: {{ template "artifactory.name" . }}
    chart: {{ template "artifactory.chart" . }}
    component: {{ .Values.rtfs.name }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
data:
  {{- range $key, $value := .Values.rtfs.persistence.federationProperties }}
    {{ $key }}: {{ tpl ($value | default "") . | quote }}
    {{- end }}
  {{- end }}