replicaCount: 7
common:
  persistence:
    size: 500Gi
rabbitmq:
  replicaCount: 3
  memoryHighWatermark:
    enabled: true
    type: "absolute"
    value: 2500MB
  maxAvailableSchedulers: "4"
  onlineSchedulers: "4"
  resources:
    requests:
      memory: "512Mi"
      cpu: "500m"
    limits:
      memory: "3Gi"
      cpu: "3"

postgresql:
  postgresqlExtendedConf:
    maxConnections: "600"
  resources:
    requests:
      memory: "1Gi"
      cpu: "1"
    limits:
      memory: "6Gi"
      cpu: "6"

server:
  resources:
    requests:
      memory: "300Mi"
      cpu: "100m"
    limits:
      memory: "10Gi"
      cpu: "10"

analysis:
  resources:
    requests:
      memory: "300Mi"
      cpu: "50m"
    limits:
      memory: "10Gi"
      cpu: "10"

persist:
  resources:
    requests:
      memory: "300Mi"
      cpu: "50m"
    limits:
      memory: "10Gi"
      cpu: "10"

indexer:
  resources:
    requests:
      memory: "300Mi"
      cpu: "50m"
    limits:
      memory: "10Gi"
      cpu: "10"
