# Leave this file empty to ensure that CI runs builds against the default configuration in values.yaml.
# If this is an upgrade over an existing Mission Control 4.x, explicitly pass 'unifiedUpgradeAllowed=true' to upgrade
unifiedUpgradeAllowed: true
distribution:
  jfrogUrl: http://artifactory-artifactory.rt:8082
