databaseUpgradeReady: true
artifactory:
  joinKey: EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
  masterKey: FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
  persistence:
    enabled: false
# Remove extraEnvironmentVariables 7.45.x onwards
  extraEnvironmentVariables:
    - name: JF_JFCONNECT_ENABLED
      value: "false"
  replicator:
    enabled: true
    ingress:
      name:
      hosts: []
      className: "testclass1"
    trackerIngress:
      enabled: true
      className: "testclass2"
  resources:
    requests:
      memory: "4Gi"
      cpu: "2"
    limits:
      memory: "6Gi"
      cpu: "4"
  javaOpts:
    xms: "4g"
    xmx: "4g"

access:
  accessConfig:
    security:
      tls: true
  resetAccessCAKeys: true

postgresql:
  postgresqlPassword: password
  postgresqlExtendedConf:
    maxConnections: 102
  persistence:
    enabled: false

rbac:
  create: true
serviceAccount:
  create: true
  automountServiceAccountToken: true

ingress:
  enabled: true
  className: "testclass"
  hosts:
    - demonow.xyz
nginx:
  enabled: false
jfconnect:
  enabled: true
  resources:
    requests:
      memory: "100Mi"
      cpu: "100m"
    limits:
      memory: "1Gi"
      cpu: "1"
mc:
  enabled: true
splitServicesToContainers: true

router:
  resources:
    requests:
      memory: "100Mi"
      cpu: "100m"
    limits:
      memory: "1Gi"
      cpu: "1"
frontend:
  resources:
    requests:
      memory: "100Mi"
      cpu: "100m"
    limits:
      memory: "1Gi"
      cpu: "1"
metadata:
  resources:
    requests:
      memory: "100Mi"
      cpu: "100m"
    limits:
      memory: "1Gi"
      cpu: "1"
event:
  resources:
    requests:
      memory: "100Mi"
      cpu: "100m"
    limits:
      memory: "1Gi"
      cpu: "1"
integration:
  resources:
    requests:
      memory: "100Mi"
      cpu: "100m"
    limits:
      memory: "1Gi"
      cpu: "1"
observability:
  resources:
    requests:
      memory: "100Mi"
      cpu: "100m"
    limits:
      memory: "1Gi"
      cpu: "1"
