# Leave this file empty to ensure that CI runs builds against the default configuration in values.yaml.
databaseUpgradeReady: true

# To Fix ct tool --reuse-values - PASSWORDS ERROR: you must provide your current passwords when upgrade the release
postgresql:
  auth:
    password: "password"
  primary:
    persistence:
      enabled: false

artifactory:
  persistence:
    enabled: false
  database:
    maxOpenConnections: 80
  tomcat:
    connector:
      maxThreads: 200
  resources:
    requests:
      memory: "4Gi"
      cpu: "2"
    limits:
      memory: "6Gi"
      cpu: "4"
  javaOpts:
    xms: "4g"
    xmx: "6g"
access:
  database:
    maxOpenConnections: 80
  tomcat:
    connector:
      maxThreads: 50
router:
  resources:
    requests:
      memory: "100Mi"
      cpu: "100m"
    limits:
      memory: "1Gi"
      cpu: "1"
frontend:
  resources:
    requests:
      memory: "100Mi"
      cpu: "100m"
    limits:
      memory: "1Gi"
      cpu: "1"
metadata:
  database:
    maxOpenConnections: 80
  resources:
    requests:
      memory: "100Mi"
      cpu: "100m"
    limits:
      memory: "1Gi"
      cpu: "1"
event:
  resources:
    requests:
      memory: "100Mi"
      cpu: "100m"
    limits:
      memory: "1Gi"
      cpu: "1"
jfconnect:
  resources:
    requests:
      memory: "100Mi"
      cpu: "100m"
    limits:
      memory: "1Gi"
      cpu: "1"
observability:
  resources:
    requests:
      memory: "100Mi"
      cpu: "100m"
    limits:
      memory: "1Gi"
      cpu: "1"

rtfs:
  enabled: true

jfbus:
  enabled: true
