# If this is an upgrade over an existing platform chart, explicitly pass 'gaUpgradeReady=true' to upgrade
gaUpgradeReady: true

# Xray pod split enabled
xray:
  enabled: true
  splitXraytoSeparateDeployments:
    fullSplit: true
